### ISSUE TITLE
Bitstream error

### ISSUE THREAD

**Issue by DrAvedi** [nullobject/openfpga-tecmo#1]
Hi there! firstly, thanks for contributing to the growing number of cores for Pocket. It's a really exciting time for handheld gaming thanks to you and your contemporaries!

I'm probably doing something wrong, since I've seen many videos of the core running Rygar properly. I have been consistently getting bitstream errors when I try to load the game. I've placed a merged and unzipped rom folder for Rygar in the "Assets/common" directory, but the core gives a missing bitstream error. The Pocket wants to see a file called "bitstream.rbf_r" which can't be found in the Core folder.

Any help would be appreciated!

**Comment by nullobject** [comment]
Hi @DrAvedi, sorry you are having issues. The `bitstream.rbf_r` file is the core to be loaded on the FPGA, so if the Pocket can't find it then it is never going to load.

Double-check you have copied everything across properly. You should have a `bitstream.rbf_r` file in the `Cores/nullobject.tecmo` directory on your Pocket. It is definitely in the ZIP file, so something may have gone wrong when you copied it.

Let me know how you go.

**Comment by DrAvedi** [comment]
Thanks for getting back to me.

I'm not seeing the `bitstream.rbf_r` file in the directory you mentioned. Neither in the ZIP I downloaded from your GitHub repository, nor in the Pocket directory after the file transfer. I did struggle when I first installed the Mazamars312 Neo Geo core a couple weeks ago, but I eventually got it working after much Googling and tinkering. This may be another instance of getting to know the installation process.

When I navigate to the `Cores/nullobject.tecmo` directory here in the GitHub repository, I don't see the `bitstream.rbf_r` file. Could it be possible that it was accidentally deleted at some point after initial upload? That would account for some of the successful installations I've seen online, and my subsequent failure to install the core properly.

**Comment by nullobject** [comment]
> When I navigate to the Cores/nullobject.tecmo directory here in the GitHub repository, I don't see the bitstream.rbf_r file. Could it be possible that it was accidentally deleted at some point after initial upload? That would account for some of the successful installations I've seen online, and my subsequent failure to install the core properly.

The ZIP file isn't in the repository, it's only part of the release assets.

Are you downloading the actual `pocket-tecmo-1.0.zip` release? https://github.com/nullobject/openfpga-tecmo/releases/tag/v1.0

**Comment by DrAvedi** [comment]
Thanks for holding my hand through all this. Indeed, I was downloading the wrong ZIP.

I'm new to GitHub and haven't quite gotten the hang of protocol on here. I've got Rygar running now and look forward to the full release of this core!
