### ISSUE TITLE
Flash White Screen

### ISSUE THREAD

**Issue by Cjv5000** [nullobject/openfpga-tecmo#2]
Good Evening, thank you for contributing to the cores for the Analogue Pocket, I was able to get the core to load no problem but after I restarted the Pocket I get a Flashing white screen when trying to load the Tecmo core.  This issues seems to be only linked to the Tecmo cores all the other ones work fine.

**Comment by nullobject** [comment]
Hey, thanks for reporting the issue. Do you still have this problem?

**Comment by Cjv5000** [comment]
No I do not I fixed it by reformatting the sd and reinstalling itOn Sep 11, 2022, at 19:11, Joshua Bassett ***@***.***> wrote:﻿
Do you still have this problem?
