### ISSUE TITLE
Error in framework - Missing 'ROM' id: 1

### ISSUE THREAD

**Issue by espiox** [nullobject/openfpga-tecmo#4]
I followed the instructions to unzip the roms to the common folder (common/rygar, common/gemini etc) but when I try to run them I get the above error. I had Rygar running in 1.0, but this doesn't seem to work in 2.0.

Looking at the JSON files, it's looking for rygar.rom - is this just a renamed zip file, or a different format entirely?

**Comment by Noname1122** [comment]
Heya! I just wanted to second this. I'm not sure how to get a ROM working. My Rygar worked in 1.0, but the same folder in the same place doesn't seem to work anymore. Should it be renamed, or is a different file format necessary?
I similarly tried downloads for Silkworm and Gemini Wing, in what seemed to be the same formats as I previously had Rygar, but I'm not having any luck.

I've also tried a number of versions of .zips simply renamed to .rom, but I'm not having luck there either. Maybe the wrong .zip versions?
Any guidance would be appreciated. Thanks!!

**Comment by nullobject** [comment]
Hi folks, sorry for the confusion. I haven't finished writing the install instructions for this release yet, given that you need to generate the ROMs using the MRA tool.

I am writing up some proper install instructions now...

**Comment by nullobject** [comment]
Ok, I have added installation instructions to the release:

https://github.com/nullobject/openfpga-tecmo/releases/tag/v2.0

Note: you will need to re-download the release ZIP file as I have added some files to it.

**Comment by Noname1122** [comment]
Just wanted to confirm that that did the trick. Thanks so much, sir!

**Comment by nullobject** [comment]
@Noname1122 Glad to hear it.
